basepath = "."

locales = [
    "de",
    "en-CA",
    "en-GB",
    "fr",
    "it"
]

[[paths]]
    reference = "en-US/*.ftl"
    l10n = "{locale}/*.ftl"

[[paths]]
    reference = "en-US/subset/import_bookmarks_onboarding_2023.ftl"
    l10n = "{locale}/subset/import_bookmarks_onboarding_2023.ftl"
    locales = [
        "de",
        "fr"
    ]

[[paths]]
    reference = "en-US/subset/pin_taskbar_fox_doodle_2023.ftl"
    l10n = "{locale}/subset/pin_taskbar_fox_doodle_2023.ftl"
    locales = [
        "de",
        "fr"
    ]

[[paths]]
    reference = "en-US/subset/vpn_spotlight_modal_2023.ftl"
    l10n = "{locale}/subset/vpn_spotlight_modal_2023.ftl"
    locales = [
        "de",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/windows_bg_notifications_2023.ftl"
    l10n = "{locale}/subset/windows_bg_notifications_2023.ftl"
    locales = [
        "de",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/device_migration_2023.ftl"
    l10n = "{locale}/subset/device_migration_2023.ftl"
    locales = [
        "de",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/fox_doodle_set_to_default_early_day_graphics_2023.ftl"
    l10n = "{locale}/subset/fox_doodle_set_to_default_early_day_graphics_2023.ftl"
    locales = [
        "de",
        "en-CA",
        "en-GB",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/fox_doodle_pin_to_taskbar_early_day_graphics_2023.ftl"
    l10n = "{locale}/subset/fox_doodle_pin_to_taskbar_early_day_graphics_2023.ftl"
    locales = [
        "de",
        "en-CA",
        "en-GB",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/backgroundtaskmessage_pip_notification_2023.ftl"
    l10n = "{locale}/subset/backgroundtaskmessage_pip_notification_2023.ftl"
    locales = [
        "en-CA",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/new_user_test_copy_about_privacy_speed_security_fx120_2023.ftl"
    l10n = "{locale}/subset/new_user_test_copy_about_privacy_speed_security_fx120_2023.ftl"
    locales = [
        "de",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/new_tab_microsurvey_relevance_satisfaction_2024.ftl"
    l10n = "{locale}/subset/new_tab_microsurvey_relevance_satisfaction_2024.ftl"
    locales = [
        "de",
        "en-CA",
        "en-GB",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/ask_windows_mac_desktop_early_day_profiles_about_their_firefox_use_case_2024.ftl"
    l10n = "{locale}/subset/ask_windows_mac_desktop_early_day_profiles_about_their_firefox_use_case_2024.ftl"
    locales = [
        "de",
        "en-CA",
        "en-GB",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/discovery_of_search_sap_existing_it_de_fr_2024.ftl"
    l10n = "{locale}/subset/discovery_of_search_sap_existing_it_de_fr_2024.ftl"
    locales = [
        "de",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/fx_view_discoverability_early_day_users_2024.ftl"
    l10n = "{locale}/subset/fx_view_discoverability_early_day_users_2024.ftl"
    locales = [
        "de",
        "en-CA",
        "en-GB",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/localized_privacy_addon_recommendations_onboarding_2024.ftl"
    l10n = "{locale}/subset/localized_privacy_addon_recommendations_onboarding_2024.ftl"
    locales = [
        "de",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/pdf_annotations_highlight_already_default_handler_2024.ftl"
    l10n = "{locale}/subset/pdf_annotations_highlight_already_default_handler_2024.ftl"
    locales = [
        "de",
        "en-CA",
        "en-GB",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/microsurvey_sync_csat_2024_2024.ftl"
    l10n = "{locale}/subset/microsurvey_sync_csat_2024_2024.ftl"
    locales = [
        "de",
        "en-CA",
        "en-GB",
        "fr"
    ]

[[paths]]
    reference = "en-US/subset/microsurvey_search_csat_2024_2024.ftl"
    l10n = "{locale}/subset/microsurvey_search_csat_2024_2024.ftl"
    locales = [
        "de",
        "en-CA",
        "en-GB",
        "fr"
    ]

[[paths]]
    reference = "en-US/subset/recommend_bookmark_toolbar_existing_user_2024.ftl"
    l10n = "{locale}/subset/recommend_bookmark_toolbar_existing_user_2024.ftl"
    locales = [
        "de",
        "en-CA",
        "en-GB",
        "fr",
        "it"
    ]
