# All files translated by the community by at least some locales should
# be covered by the [[paths]] in this file.

basepath = "."

locales = [
    "de",
    "fr",
    "it"
]

[[paths]]
    reference = "en-US/*.ftl"
    l10n = "{locale}/*.ftl"

[[paths]]
    reference = "en-US/subset/import_bookmarks_onboarding_2023.ftl"
    l10n = "{locale}/subset/import_bookmarks_onboarding_2023.ftl"
    locales = [
        "de",
        "fr"
    ]

[[paths]]
    reference = "en-US/subset/pin_taskbar_fox_doodle_2023.ftl"
    l10n = "{locale}/subset/pin_taskbar_fox_doodle_2023.ftl"
    locales = [
        "de",
        "fr"
    ]

[[paths]]
    reference = "en-US/subset/vpn_spotlight_modal_2023.ftl"
    l10n = "{locale}/subset/vpn_spotlight_modal_2023.ftl"
    locales = [
        "de",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/windows_bg_notifications_2023.ftl"
    l10n = "{locale}/subset/windows_bg_notifications_2023.ftl"
    locales = [
        "de",
        "fr",
        "it"
    ]

[[paths]]
    reference = "en-US/subset/device_migration_2023.ftl"
    l10n = "{locale}/subset/device_migration_2023.ftl"
    locales = [
        "de",
        "fr",
        "it"
    ]
